site_name: Keep
theme:
  name: material
  logo: assets/pp.png
  favicon: assets/pp.png
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - search.suggest
plugins:
  - search:
      lang: 
        - zh
        - en
  - social:
      cards_layout: default/variant

nav:
  - C++ :
    - cpp/index.md
    - Page1 : cpp/page-1.md
    - Pagen : cpp/page-n.md

