site_name: Keep
theme:
  name: material
  logo: assets/pp.png
  favicon: assets/pp.png
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - search.suggest
plugins:
  - search:
      lang: 
        - zh
        - en
  - social:
      cards_layout: default/variant

nav:
  - C++ :
    - 目录: cpp/index.md
    - 运算符重载: cpp/operator-override.md
    - 指针 : cpp/pointer.md

