site_name: Keep
theme:
  name: material
  logo: docs/pp.png
  favicon: docs/pp.png
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - search.suggest
plugins:
  - search:
      lang: 
        - zh
        - en
  - social:
      cards_layout: default/variant

